#!/bin/bash
 git rm 52binge.blog.src.md
 git rm ai2/index.html
 git rm ai2/index.md
 git rm ai2018-2/AB.ipynb
 git rm ai2018-2/index.html
 git rm ai2018/index.html
 git rm ai33/index.html
 git rm article_bak/ELMo.html
 git rm article_bak/chatbot-index.html
 git rm article_bak/offer-Array-LinkedList.html
 git rm article_bak/offer-BinaryTree.html
 git rm disable/Decision_Tree_part1.html
 git rm disable/chatbot-research10.html
 git rm disable/chatbot-research9.html
 git rm how/index.html
 git rm interview/index.html
 git rm japan/index.html
 git rm ks/index.html
 git rm macao/index.html
 git rm myfer/index.html
 git rm mythaitrip/index.html
 git rm mytrip_for_gz/index.html
 git rm mytrip_macau/index.html
 git rm mytrip_macau/index.md
 git rm mytrip_thai/index.html
 git rm mytrip_thai/index.md
 git rm pro/index.html
 git rm pro/index.md
 git rm pro/pro2/index.html
 git rm pro/pro2/index.md
 git rm pro/pro3/index.html
 git rm pro/pro3/index.md
 git rm pro/pro4/index.html
 git rm pro/pro4/index.md
 git rm pro/proj/index.html
 git rm pro/proj/index.md
 git rm pro/proj_dmp/index.html
 git rm pro/proj_dmp/index.md
 git rm pro1_interest/index.html
 git rm pro2_recommendation/index.html
 git rm reading/index.html
 git rm search.xml
 git rm sggo/index.html
 git rm sggo2/index.html
 git rm sggo3/index.html
 git rm sggo3/index2.html
 git rm sggo5/index.html
 git rm sggo6/index.html
 git rm spo/index.html
 git rm spo/index2.html
 git rm tmp/index.html
